set echo on
set timing on
set lines 300
set pages 1000
rem set autotrace traceonly explain
set autotrace on
spool eclubinter.txt
SELECT count(1) 
FROM 
	CURRENT_POLICIES CP 
	INNER JOIN ENDPOLICY ALL_END_POL ON CP.STRUCTURAL_END_TID = ALL_END_POL.TECHNICALIDENTIFIER 
	INNER JOIN ENDPOLICY FULL_6601_END_POL ON (FULL_6601_END_POL.TECHNICALIDENTIFIER = COALESCE(ALL_END_POL.FULL_PREVIOUS_TID, ALL_END_POL.TECHNICALIDENTIFIER ))
	LEFT OUTER JOIN ENDPOLICY_CF ECF ON(ECF.PARENT_OID=FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN ENDPOLICY_PRODUCTPAR ENDPAR ON (ENDPAR.PARENT_OID = FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN PRODUCT P ON (P.TECHNICALIDENTIFIER = FULL_6601_END_POL.POL_PRODUCT_TID)
	LEFT OUTER JOIN CURRENCY C ON C.TECHNICALIDENTIFIER = FULL_6601_END_POL.POL_CURRENCY_TID 
	LEFT OUTER JOIN (RoleToRoleTarget RT INNER JOIN RolePayer RP On RP.TECHNICALIDENTIFIER = RT.Role_TID) 
		ON RT.Role_Target_TID = CP.POL_POLICY_SID 
	LEFT OUTER JOIN POL_SIGN_DATE PSD ON PSD.POL_NUMBER = CP.POL_NUMBER 
	LEFT OUTER JOIN PAYSTAT ON CP.POL_POLICY_SID = PAYSTAT.POLICY_TID 
	LEFT OUTER JOIN POLICY_EVAL ON CP.POL_NUMBER = POLICY_EVAL.IDPOLICE 
	LEFT OUTER JOIN ENDPOLICY_INDEXSETTING EI ON EI.parent_OID = FULL_6601_END_POL.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN CLASSESRESULTAT CR ON CR.ID_POLICE = FULL_6601_END_POL.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN ENDCOVERAGE ON (ENDCOVERAGE.EndorsedPolicy_TID = CP.STRUCTURAL_END_TID and InvCov_InvestmentStrategy_TID is not null) 
	LEFT OUTER JOIN INVSTRAT ON (ENDCOVERAGE.InvCov_InvestmentStrategy_TID = INVSTRAT.TECHNICALIDENTIFIER) 
	LEFT OUTER JOIN INVSTRATDEF ID ON (InvestStrategyDefinition_TID = ID.TECHNICALIDENTIFIER )
	LEFT OUTER JOIN ROLETOROLETARGET RT2 ON (RT2.ROLE_TARGET_TID = FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN BROKER ON (BROKER.TECHNICALIDENTIFIER = RT2.ROLE_TID)
	LEFT OUTER JOIN DISTRIBUTIONNETWORK_STRUCT ON (DISTRIBUTIONNETWORK_STRUCT.DISTRIBUTIONPARTNER_TID = BROKER.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN DISTRIBUTIONNETWORK ON (DISTRIBUTIONNETWORK.TECHNICALIDENTIFIER = DISTRIBUTIONNETWORK_STRUCT.PARENT_OID)
	LEFT OUTER JOIN  DISTRIBUTIONNETWORK_PRODUCT ON (DISTRIBUTIONNETWORK_PRODUCT.PARENT_OID = DISTRIBUTIONNETWORK.TECHNICALIDENTIFIER 
			AND DISTRIBUTIONNETWORK_PRODUCT.PRODUCT_TID = P.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN MAX_DATE ON CP.POL_POLICY_SID = MAX_DATE.TECH_ID_POL 
	LEFT OUTER JOIN TAXFRAMEWORK TaxFwk ON FULL_6601_END_POL.TaxFramework_TID = TaxFwk.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN TAXCALCHIST ON TAXCALCHIST.Owner_TID = FULL_6601_END_POL.technicalidentifier 
	LEFT OUTER JOIN TAXCALCHIST_PAR ON TAXCALCHIST_PAR.Parent_OID = TAXCALCHIST.technicalidentifier 
WHERE ALL_END_POL.End_Internal_Nbr IS NOT NULL;
spool off;

