explain plan for
WITH MAX_DATE_REGLEMENT AS (
	select 
	BP.PARENT_OID, 
	max(BP.Cal_Date) as dateReglement 
	FROM Bill_ProcessDetails BP WHERE BP.BILLSTATUS_EID='PAID' group by BP.PARENT_OID 
	) 
SELECT DISTINCT 
	B.EXTERNALID as ID, 
	B.STARTDATE as DATEECHEANCE, 
	B.STARTDATE as DATEDEBUT, 
	B.ENDDATE, 
	B.ISSUEDATE as DATEENVOI, 
	B.TYPE_EID as TYPE, 
	B.BILLSTATUS_EID as STATUT, 
	B.TOTALAMOUNT_VALUE, 
	C.ISOCODE, 
	B.OUTSTANDINGAMOUNT_VALUE, 
	CASE B.OUTSTANDINGAMOUNT_VALUE  
    WHEN 0 THEN MAX_DATE_REGLEMENT.dateReglement  
    ELSE NULL  
    END AS DATEREGLEMENT, 
	E.POL_NUMBER 
	FROM BILL B 
	INNER JOIN ENDPOLICY E ON E.TECHNICALIDENTIFIER = B.Origin_TID  
	LEFT OUTER JOIN MAX_DATE_REGLEMENT ON MAX_DATE_REGLEMENT.PARENT_OID = B.TECHNICALIDENTIFIER 
	LEFT JOIN CURRENCY C ON C.TECHNICALIDENTIFIER = B.CURRENCY_TID 
	WHERE B.BILLSTATUS_EID <> 'NEW' and B.BILLSTATUS_EID <> 'SCHEDULED'  and B.BILLSTATUS_EID <> 'ADJUSTED' and E.END_STATUS_EID='VALIDATED';
