set autotrace on
set timing on
WITH MAX_DATE_REGLEMENT AS (
	select 
	BP.PARENT_OID, 
	max(BP.Cal_Date) as dateReglement 
	FROM Bill_ProcessDetails BP WHERE BP.BILLSTATUS_EID='PAID' group by BP.PARENT_OID 
	) 
SELECT count(1)
	FROM BILL B 
	INNER JOIN ENDPOLICY E ON E.TECHNICALIDENTIFIER = B.Origin_TID  
	LEFT OUTER JOIN MAX_DATE_REGLEMENT ON MAX_DATE_REGLEMENT.PARENT_OID = B.TECHNICALIDENTIFIER 
	LEFT JOIN CURRENCY C ON C.TECHNICALIDENTIFIER = B.CURRENCY_TID 
	WHERE B.BILLSTATUS_EID <> 'NEW' and B.BILLSTATUS_EID <> 'SCHEDULED'  and B.BILLSTATUS_EID <> 'ADJUSTED' and E.END_STATUS_EID='VALIDATED';
