explain plan for
SELECT 
    c.TECHNICALIDENTIFIER, 
    b.EXTERNALID, 
    c.transactionpaymentmode_eid AS VALUE, 
    c.VALUEDATE, 
    c.RECEIVEDAMOUNT_VALUE, 
    c.STATEMENTNUMBER, 
    act.LABEL, 
    I.INSTANCEID 
	FROM CONTRIBUTION c 
    INNER JOIN BILL_CONTRIBUTIONS bc 
        ON c.TECHNICALIDENTIFIER = bc.billcontribution_tid 
    INNER JOIN BILL b 
        ON bc.parent_oid = b.TECHNICALIDENTIFIER 
    INNER JOIN ENDPOLICY E ON E.TECHNICALIDENTIFIER = B.Origin_TID 
    LEFT JOIN ACCOUNT act 
        ON c.BANKACCOUNT_TID=act.technicalidentifier 
    LEFT JOIN (INSTANCE_AFFECTATIONS IA 
        INNER JOIN INSTANCE I 
            ON IA.PARENT_OID=I.TECHNICALIDENTIFIER 
            ) ON IA.TARGETID=bc.BILLCONTRIBUTION_TID 
	WHERE c.STATUS_EID='INFORCE'  
    AND  b.BILLSTATUS_EID NOT IN ('NEW', 'SCHEDULED', 'ADJUSTED') AND E.END_STATUS_EID='VALIDATED';
