COLUMN SQL_TEXT FORMAT a30  wrap 
COLUMN SCH FORMAT a3
COLUMN ELAPSED FORMAT 99999999999
set lines 250
set pages 500

spool q_sts;
SELECT SQL_ID, PARSING_SCHEMA_NAME AS "SCH", SQL_TEXT, 
       ELAPSED_TIME AS "ELAPSED", BUFFER_GETS
FROM   TABLE( DBMS_SQLTUNE.SELECT_SQLSET( 'STS01' ) )
order by elapsed_time;
spool off;
