set echo on
set timing on
set lines 300
set pages 1000
rem set autotrace traceonly explain
set autotrace on
spool eclubinter.txt
SELECT DISTINCT 
	ALL_END_POL.POL_NUMBER, 
	CR.CLASSEFONDSINVESTI, 
	P.CODE, 
	ENDPAR.PRSTRPRODUCTLINE_VAL AS LIGNEMETIER, 
	ALL_END_POL.POL_STATUS_EID AS EXTERNALID, 
	C.ISOCODE, 
	ALL_END_POL.PAYMENTMODE_EID AS VALUE, 
	ALL_END_POL.POL_EFFECTIVEDATE, 
	ALL_END_POL.POL_TERMDATE, 
	CASE 
		WHEN ALL_END_POL.PERIODICITY_EID = 'MON' THEN ADD_MONTHS(MAX_DATE.BILL_DATE,1) 
		WHEN ALL_END_POL.PERIODICITY_EID = 'QUA' THEN ADD_MONTHS(MAX_DATE.BILL_DATE,3) 
		WHEN ALL_END_POL.PERIODICITY_EID = 'SEM' THEN ADD_MONTHS(MAX_DATE.BILL_DATE,6) 
		WHEN ALL_END_POL.PERIODICITY_EID = 'ANN' THEN ADD_MONTHS(MAX_DATE.BILL_DATE,12) 
	END AS MODIFIEDDATE, 
	ALL_END_POL.POL_COUNTRYOFLAW_EID AS FISCALITE, 
	ENDPAR.DURATION_VAL, 
	ENDPAR.DURATIONUNIT_EID AS UNITEDUREE, 
	ECF.POSTRIDDISTRIBUTOR_VAL, 
	ECF.POBOOMANDATINTERMEDIATION_VAL, 
	ECF.POSTRCIRCULARLETTER_VAL, 
	PSD.CPSIGNEE, 
	PSD.DATECPSIGNEE AS DATECPSIGNEE, 
	ECF.POSTRMODEENVCOURRIER_VAL, 
	(select EACC.IBAN from EXTERNALACCOUNT EACC where EACC.OWNER_TID = RP.TECHNICALIDENTIFIER and eacc.isdefault='true' fetch first row only) as IBAN, 
	PAYSTAT.REMIND_STATUS AS STATUTPAYMENT, 
	POLICY_EVAL.EVAL AS EVAL, 
	ECF.POSTRBULLETINSOUS_VAL, 
	CASE 
		WHEN ALL_END_POL.pol_enddate BETWEEN CURRENT_DATE AND ADD_MONTHS(CURRENT_DATE, -6) and ALL_END_POL.POL_STATUS_EID in ('CANC', 'CLAIMED', 'CLOSE', 'DEATH_CL', 'INAC', 'NOTPROC', 'RENUNC', 'SURREN', 'TERM', 'TRANSF') THEN 'false' 
		WHEN ALL_END_POL.pol_enddate BETWEEN CURRENT_DATE AND ADD_MONTHS(CURRENT_DATE, -6) and ALL_END_POL.POL_STATUS_EID in ('SURREN') THEN 'true' 
		WHEN ALL_END_POL.POL_STATUS_EID in ('FORCE') THEN 'true' 
		ELSE 'false' 
	END AS VISIBLEEXTERIEUR, 
	CASE WHEN EI.INDEXATIONTYPE_EID = 'FISCAL_GAIN' THEN 'true' ELSE 'false' END AS MAXIMUMDEDUCTIBLE, 
	ENDPAR.PRSTRPRODUCTCODE_VAL AS OLDCODEPRODUIT, 
	ID.identifier as STRATEGIEINVESTISSEMENT, 
	coalesce(ECF.poStrCommercialLabel_VAL, DISTRIBUTIONNETWORK_PRODUCT.COMMERCIALNAME, P.name) as LIBELLEPRODUITLABELLISE, 
	TaxFwk.NAME AS MANDATFISCALTYPE, 
	TAXCALCHIST_PAR.TUBOOFISCALWITHMANDATE_VAL AS MANDATFISCALVALEUR 
FROM 
	CURRENT_POLICIES CP 
	INNER JOIN ENDPOLICY ALL_END_POL ON CP.STRUCTURAL_END_TID = ALL_END_POL.TECHNICALIDENTIFIER 
	INNER JOIN ENDPOLICY FULL_6601_END_POL ON (FULL_6601_END_POL.TECHNICALIDENTIFIER = COALESCE(ALL_END_POL.FULL_PREVIOUS_TID, ALL_END_POL.TECHNICALIDENTIFIER ))
	LEFT OUTER JOIN ENDPOLICY_CF ECF ON(ECF.PARENT_OID=FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN ENDPOLICY_PRODUCTPAR ENDPAR ON (ENDPAR.PARENT_OID = FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN PRODUCT P ON (P.TECHNICALIDENTIFIER = FULL_6601_END_POL.POL_PRODUCT_TID)
	LEFT OUTER JOIN CURRENCY C ON C.TECHNICALIDENTIFIER = FULL_6601_END_POL.POL_CURRENCY_TID 
	LEFT OUTER JOIN (RoleToRoleTarget RT INNER JOIN RolePayer RP On RP.TECHNICALIDENTIFIER = RT.Role_TID) 
		ON RT.Role_Target_TID = CP.POL_POLICY_SID 
	LEFT OUTER JOIN POL_SIGN_DATE PSD ON PSD.POL_NUMBER = CP.POL_NUMBER 
	LEFT OUTER JOIN PAYSTAT ON CP.POL_POLICY_SID = PAYSTAT.POLICY_TID 
	LEFT OUTER JOIN POLICY_EVAL ON CP.POL_NUMBER = POLICY_EVAL.IDPOLICE 
	LEFT OUTER JOIN ENDPOLICY_INDEXSETTING EI ON EI.parent_OID = FULL_6601_END_POL.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN CLASSESRESULTAT CR ON CR.ID_POLICE = FULL_6601_END_POL.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN ENDCOVERAGE ON (ENDCOVERAGE.EndorsedPolicy_TID = CP.STRUCTURAL_END_TID and InvCov_InvestmentStrategy_TID is not null) 
	LEFT OUTER JOIN INVSTRAT ON (ENDCOVERAGE.InvCov_InvestmentStrategy_TID = INVSTRAT.TECHNICALIDENTIFIER) 
	LEFT OUTER JOIN INVSTRATDEF ID ON (InvestStrategyDefinition_TID = ID.TECHNICALIDENTIFIER )
	LEFT OUTER JOIN ROLETOROLETARGET RT2 ON (RT2.ROLE_TARGET_TID = FULL_6601_END_POL.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN BROKER ON (BROKER.TECHNICALIDENTIFIER = RT2.ROLE_TID)
	LEFT OUTER JOIN DISTRIBUTIONNETWORK_STRUCT ON (DISTRIBUTIONNETWORK_STRUCT.DISTRIBUTIONPARTNER_TID = BROKER.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN DISTRIBUTIONNETWORK ON (DISTRIBUTIONNETWORK.TECHNICALIDENTIFIER = DISTRIBUTIONNETWORK_STRUCT.PARENT_OID)
	LEFT OUTER JOIN  DISTRIBUTIONNETWORK_PRODUCT ON (DISTRIBUTIONNETWORK_PRODUCT.PARENT_OID = DISTRIBUTIONNETWORK.TECHNICALIDENTIFIER 
			AND DISTRIBUTIONNETWORK_PRODUCT.PRODUCT_TID = P.TECHNICALIDENTIFIER)
	LEFT OUTER JOIN MAX_DATE ON CP.POL_POLICY_SID = MAX_DATE.TECH_ID_POL 
	LEFT OUTER JOIN TAXFRAMEWORK TaxFwk ON FULL_6601_END_POL.TaxFramework_TID = TaxFwk.TECHNICALIDENTIFIER 
	LEFT OUTER JOIN TAXCALCHIST ON TAXCALCHIST.Owner_TID = FULL_6601_END_POL.technicalidentifier 
	LEFT OUTER JOIN TAXCALCHIST_PAR ON TAXCALCHIST_PAR.Parent_OID = TAXCALCHIST.technicalidentifier 
WHERE ALL_END_POL.End_Internal_Nbr IS NOT NULL;

